version: '3.9'

services:
  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pw-that-is-n0t-used-in-prod
      - POSTGRES_USER=recurringscheduler
      - POSTGRES_DB=recurringscheduler

  frontend:
    image: ernstsen/recurringschedulerfrontend
    ports:
      - 8080:80
    environment:
      - BACKEND_URL=backend

  backend:
    image: ernstsen/recurringschedulerbackend:1.0.0-SNAPSHOT
    ports:
      - 8081:8080
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_DB_VERSION=16.0
      - QUARKUS_DATASOURCE_USERNAME=recurringscheduler
      - QUARKUS_DATASOURCE_PASSWORD=pw-that-is-n0t-used-in-prod
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/recurringscheduler
    depends_on:
      - database
    restart: unless-stopped
